name: tinh
description: A new Flutter project.

publish_to: 'none' 
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

 
  cupertino_icons: ^1.0.0
  flutter_staggered_animations: "^1.0.0"
  # font_awesome_flutter: ^9.1.0
  dio: ^4.0.0
  mobx: ^2.0.5
  flutter_spinkit: ^5.1.0
  flutter_mobx: ^2.0.2
  provider: ^6.0.1
  flutter_easyrefresh: ^2.2.1
  path_provider:
  carousel_slider: ^4.0.0
  simple_animations: ^3.0.1
  device_info: 
  awesome_dialog: ^2.1.1
  uuid: ^3.0.5
  lottie: ^1.2.1
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.5
  flutter_zoom_drawer: ^2.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.7

flutter:
  assets:
    - assets/images/
    - assets/lottie/


  uses-material-design: true

